apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: spring-sensors-producer
  namespace: tap-workload
  labels:
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
    carto.run/cluster-template-name: config-deliverable-template
    carto.run/resource-name: create-deliverable
    carto.run/supply-chain-name: source-to-url
    carto.run/template-kind: ClusterConfigTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: spring-sensors-producer
    carto.run/workload-namespace: tap-workload
spec:
  params:
  - name: gitops_ssh_secret
    value: shatkar-gaig-https
  source:
    git:
      url: https://shatkar-gaig@github.com/shatkar-gaig/tap-delivery.git
      ref:
        branch: main
    subPath: config/tap-workload/spring-sensors-producer

